### PR TITLE
Joe updates

### PR DESCRIPTION
**Pull request by joetamburro**

### CODE REVIEW

**Comment by saddington** [comment]
What's up with the job code javascript?

**Comment by joetamburro** [comment]
as far as what exactly?

**Comment by saddington** [comment]
commented out? can we deploy it?

**Comment by joetamburro** [comment]
It needs styling and what not. Just testing the functionality. Will get with you tomorrow briefly if I have any questions.

**Comment by saddington** [comment]
kk. cool. thanks joe.

**Comment by joetamburro** [comment]
no problem. should go live tomorrow.

**Pull request merged**
